<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="642ddd6c-01c4-498a-b63b-0fb869987d0e" name="Javi@JAVI-PC 2010-09-19 13:46:11" runUser="Javi-PC\Javi" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="da34d0b4-0511-46eb-bb91-669de211e68e">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Javi_JAVI-PC 2010-09-19 13_46_11">
      <DeploymentItem filename="C:\Code\WcfHttpAuth\WcfHttpAuth\bin\Debug\WcfHttpAuth.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2010-09-19T13:46:11.1517865+02:00" queuing="2010-09-19T13:46:11.3637986+02:00" start="2010-09-19T13:46:11.4098012+02:00" finish="2010-09-19T13:46:38.1663316+02:00" />
  <ResultSummary outcome="Failed">
    <Counters total="4" executed="3" error="0" failed="3" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Given_credentials_are_valid_then_should_return_200" storage="c:\code\wcfhttpauth\wcfhttpauth.integrationtests\bin\debug\wcfhttpauth.integrationtests.dll" id="d2c4f2ed-2807-a47b-bc9e-9a4b6401e12e">
      <Execution id="0c9b0697-e85a-4651-aa2f-c55ffa13dc35" />
      <TestMethod codeBase="C:/Code/WcfHttpAuth/WcfHttpAuth.IntegrationTests/bin/Debug/WcfHttpAuth.IntegrationTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="WcfHttpAuth.IntegrationTests.When_calling_a_basic_auth_service, WcfHttpAuth.IntegrationTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Given_credentials_are_valid_then_should_return_200" />
      <AspNetDevelopmentServers>
        <DevelopmentServer name="Server" pathToWebApp="..\Server" webAppRoot="http://locahost:3000" />
      </AspNetDevelopmentServers>
    </UnitTest>
    <UnitTest name="Given_credentials_are_valid_then_should_return_200" storage="c:\code\wcfhttpauth\wcfhttpauth.integrationtests\bin\debug\wcfhttpauth.integrationtests.dll" id="3d5a2998-aebd-79e2-bb3a-f979cf6d64b5">
      <Execution id="24902b5e-e124-4d83-bb61-77e65e63f899" />
      <TestMethod codeBase="C:/Code/WcfHttpAuth/WcfHttpAuth.IntegrationTests/bin/Debug/WcfHttpAuth.IntegrationTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="WcfHttpAuth.IntegrationTests.When_calling_a_wsse_auth_service, WcfHttpAuth.IntegrationTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Given_credentials_are_valid_then_should_return_200" />
    </UnitTest>
    <UnitTest name="Given_credentials_are_invalid_then_should_return_401" storage="c:\code\wcfhttpauth\wcfhttpauth.integrationtests\bin\debug\wcfhttpauth.integrationtests.dll" id="66708f93-7293-f476-715a-1f4ac9ebac9e">
      <Execution id="c0537472-f350-4cb3-b9b8-e7995c9b066c" />
      <TestMethod codeBase="C:/Code/WcfHttpAuth/WcfHttpAuth.IntegrationTests/bin/Debug/WcfHttpAuth.IntegrationTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="WcfHttpAuth.IntegrationTests.When_calling_a_basic_auth_service, WcfHttpAuth.IntegrationTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Given_credentials_are_invalid_then_should_return_401" />
      <AspNetDevelopmentServers>
        <DevelopmentServer name="Server" pathToWebApp="..\Server" webAppRoot="http://locahost:3000" />
      </AspNetDevelopmentServers>
    </UnitTest>
    <UnitTest name="Given_credentials_are_invalid_then_should_return_401" storage="c:\code\wcfhttpauth\wcfhttpauth.integrationtests\bin\debug\wcfhttpauth.integrationtests.dll" id="9566efb0-741c-90b7-c3af-168c9f4ebed6">
      <Execution id="1f3ec3c5-925c-4e6f-a6bd-6425002c4f05" />
      <TestMethod codeBase="C:/Code/WcfHttpAuth/WcfHttpAuth.IntegrationTests/bin/Debug/WcfHttpAuth.IntegrationTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="WcfHttpAuth.IntegrationTests.When_calling_a_wsse_auth_service, WcfHttpAuth.IntegrationTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Given_credentials_are_invalid_then_should_return_401" />
      <AspNetDevelopmentServers>
        <DevelopmentServer name="localhost:3000" pathToWebApp="..\Server" />
      </AspNetDevelopmentServers>
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="3d5a2998-aebd-79e2-bb3a-f979cf6d64b5" executionId="24902b5e-e124-4d83-bb61-77e65e63f899" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="66708f93-7293-f476-715a-1f4ac9ebac9e" executionId="c0537472-f350-4cb3-b9b8-e7995c9b066c" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="9566efb0-741c-90b7-c3af-168c9f4ebed6" executionId="1f3ec3c5-925c-4e6f-a6bd-6425002c4f05" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="d2c4f2ed-2807-a47b-bc9e-9a4b6401e12e" executionId="0c9b0697-e85a-4651-aa2f-c55ffa13dc35" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="24902b5e-e124-4d83-bb61-77e65e63f899" testId="3d5a2998-aebd-79e2-bb3a-f979cf6d64b5" testName="Given_credentials_are_valid_then_should_return_200" computerName="JAVI-PC" duration="00:00:02.0952330" startTime="2010-09-19T13:46:11.4208018+02:00" endTime="2010-09-19T13:46:13.8399402+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="24902b5e-e124-4d83-bb61-77e65e63f899">
      <Output>
        <ErrorInfo>
          <Message>Test method WcfHttpAuth.IntegrationTests.When_calling_a_wsse_auth_service.Given_credentials_are_valid_then_should_return_200 threw exception: 
System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:2391</Message>
          <StackTrace>    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception&amp; exception)
 --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.GetResponse()
   at WcfHttpAuth.IntegrationTests.When_calling_a_wsse_auth_service.Given_credentials_are_valid_then_should_return_200() in C:\Code\WcfHttpAuth\WcfHttpAuth.IntegrationTests\When_calling_a_wsse_auth_service.cs:line 41
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="c0537472-f350-4cb3-b9b8-e7995c9b066c" testId="66708f93-7293-f476-715a-1f4ac9ebac9e" testName="Given_credentials_are_invalid_then_should_return_401" computerName="JAVI-PC" duration="00:00:02.0084837" startTime="2010-09-19T13:46:33.9740918+02:00" endTime="2010-09-19T13:46:36.0162086+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c0537472-f350-4cb3-b9b8-e7995c9b066c">
      <Output>
        <ErrorInfo>
          <Message>Test method WcfHttpAuth.IntegrationTests.When_calling_a_basic_auth_service.Given_credentials_are_invalid_then_should_return_401 threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.</Message>
          <StackTrace>    at WcfHttpAuth.IntegrationTests.When_calling_a_basic_auth_service.Given_credentials_are_invalid_then_should_return_401() in C:\Code\WcfHttpAuth\WcfHttpAuth.IntegrationTests\When_calling_a_basic_auth_service.cs:line 31
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="1f3ec3c5-925c-4e6f-a6bd-6425002c4f05" testId="9566efb0-741c-90b7-c3af-168c9f4ebed6" testName="Given_credentials_are_invalid_then_should_return_401" computerName="JAVI-PC" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="1f3ec3c5-925c-4e6f-a6bd-6425002c4f05">
      <Output>
        <ErrorInfo>
          <Message>The web.config file for the site http://localhost:0/ contains information from a previous run.  Replacing it with the backup file (web.config.backup) should fix the issue.</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="0c9b0697-e85a-4651-aa2f-c55ffa13dc35" testId="d2c4f2ed-2807-a47b-bc9e-9a4b6401e12e" testName="Given_credentials_are_valid_then_should_return_200" computerName="JAVI-PC" duration="00:00:02.0074264" startTime="2010-09-19T13:46:36.0962132+02:00" endTime="2010-09-19T13:46:38.1093283+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="0c9b0697-e85a-4651-aa2f-c55ffa13dc35">
      <Output>
        <ErrorInfo>
          <Message>Test method WcfHttpAuth.IntegrationTests.When_calling_a_basic_auth_service.Given_credentials_are_valid_then_should_return_200 threw exception: 
System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:3000</Message>
          <StackTrace>    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception&amp; exception)
 --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.GetResponse()
   at WcfHttpAuth.IntegrationTests.When_calling_a_basic_auth_service.Given_credentials_are_valid_then_should_return_200() in C:\Code\WcfHttpAuth\WcfHttpAuth.IntegrationTests\When_calling_a_basic_auth_service.cs:line 42
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>